name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  MLFLOW_ALLOW_FILE_STORE: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USER: ${{ secrets.HF_USER }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub-Actions-Bot"
          git remote add hf https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/$HF_USER/fruitcluster-ai || true
          git push hf main --force
